package ca.bc.gov.health.test.constants;

public interface SimulationConstants {
    
    String DB_URL = "PLR_TEST_HARNESS_DB_URL";
    String DB_USER = "PLR_TEST_HARNESS_DB_USER";
    String DB_PASSWORD = "PLR_TEST_HARNESS_DB_PW";

    String COMMON_DEV_LOGIN_AUTH_URL = "PLR_TEST_HARNESS_COMMON_MRG_LOGIN_AUTH_URL";
    
    String COMMON_LOGIN_AUTH_GRANT_TYPE = "PLR_TEST_HARNESS_COMMON_LOGIN_AUTH_GRANT_TYPE";
    String COMMON_LOGIN_AUTH_CLIENT_IDS = "PLR_TEST_HARNESS_COMMON_LOGIN_AUTH_CLIENT_IDS";
    String COMMON_LOGIN_AUTH_CLIENT_SECRETS_MRG = "PLR_TEST_HARNESS_COMMON_LOGIN_AUTH_CLIENT_SECRETS_MRG";
    
   
    String PLR_MRG_DB_URL = "PLR_MRG_DB_URL";
    String PLR_MRG_DB_USER = "PLR_MRG_DB_USER";
    String PLR_MRG_DB_PASSWORD = "PLR_MRG_DB_PW";

    String PLR_MRG_API_HOST_URL = "PLR_MRG_API_HOST_URL";
    String PLR_MRG_HEADER_API_HOST = "PLR_MRG_HEADER_API_HOST";
    
    String HEADER_CONTENT_TYPE="HEADER_CONTENT_TYPE";
    String HEADER_USER_ID="HEADER_USER_ID";
    String HEADER_PLR_ROLE="HEADER_PLR_ROLE";
    String HEADER_ORG_ID="HEADER_ORG_ID";
}
