version: '1.0'

services:
  backend:
    container_name: backend
    build: 
      context: ../backend
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "9080:9080"
    env_file:
      - ./backend.env
  frontend:
    container_name: frontend
    build: ../frontend
    ports:
      - "9090:9090"
    env_file:
      - ./frontend.env